[2025-08-04T20:39:24.230+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T20:39:24.237+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_generator.generator_account_data scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-08-04T20:39:24.240+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_generator.generator_account_data scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-08-04T20:39:24.240+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T20:39:24.244+0000] {taskinstance.py:2890} INFO - Executing <Task(KafkaProduceOperator): generator_account_data> on 2025-03-16 00:00:00+00:00
[2025-08-04T20:39:24.248+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3098) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T20:39:24.249+0000] {standard_task_runner.py:72} INFO - Started process 3100 to run task
[2025-08-04T20:39:24.248+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_generator', 'generator_account_data', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/account_generator.py', '--cfg-path', '/tmp/tmp3x4s3vxe']
[2025-08-04T20:39:24.249+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask generator_account_data
[2025-08-04T20:39:24.266+0000] {task_command.py:467} INFO - Running <TaskInstance: account_generator.generator_account_data scheduled__2025-03-16T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T20:39:24.294+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='account_generator' AIRFLOW_CTX_TASK_ID='generator_account_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-08-04T20:39:24.295+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T20:39:24.302+0000] {kafka_operator.py:16} INFO - Producing 100 records to account_data at broker:29092
[2025-08-04T20:39:24.304+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T20:39:24.305+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=account_generator, task_id=generator_account_data, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250804T203924, end_date=20250804T203924
[2025-08-04T20:39:24.350+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-04T20:39:24.358+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T20:39:24.360+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
