[2025-08-04T22:53:15.822+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T22:53:15.850+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stream_generator.generator_stream_data scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-08-04T22:53:15.863+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stream_generator.generator_stream_data scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-08-04T22:53:15.863+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T22:53:15.877+0000] {taskinstance.py:2890} INFO - Executing <Task(StreamProduceOperator): generator_stream_data> on 2025-01-19 00:00:00+00:00
[2025-08-04T22:53:15.889+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T22:53:15.897+0000] {standard_task_runner.py:72} INFO - Started process 330 to run task
[2025-08-04T22:53:15.903+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stream_generator', 'generator_stream_data', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '635', '--raw', '--subdir', 'DAGS_FOLDER/streams_generator.py', '--cfg-path', '/tmp/tmp9kpri663']
[2025-08-04T22:53:15.909+0000] {standard_task_runner.py:105} INFO - Job 635: Subtask generator_stream_data
[2025-08-04T22:53:16.003+0000] {task_command.py:467} INFO - Running <TaskInstance: stream_generator.generator_stream_data scheduled__2025-01-19T00:00:00+00:00 [running]> on host 57a05139e7f0
[2025-08-04T22:53:16.146+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='stream_generator' AIRFLOW_CTX_TASK_ID='generator_stream_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-08-04T22:53:16.148+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T22:53:16.191+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T22:53:16.204+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-3:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Broker version identified as 2.6
[2025-08-04T22:53:16.206+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T22:53:16.224+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/streams_kafka_operator.py", line 48, in execute
    transaction = self.generate_streams_data(row_num)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/streams_kafka_operator.py", line 26, in generate_streams_data
    song_name = fake.song_name()
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/faker/proxy.py", line 130, in __getattr__
    return getattr(self._factories[0], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Generator' object has no attribute 'song_name'. Did you mean: 'month_name'?
[2025-08-04T22:53:16.252+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=stream_generator, task_id=generator_stream_data, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250804T225315, end_date=20250804T225316
[2025-08-04T22:53:16.342+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T22:53:16.345+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 635 for task generator_stream_data ('Generator' object has no attribute 'song_name'; 330)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/streams_kafka_operator.py", line 48, in execute
    transaction = self.generate_streams_data(row_num)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/streams_kafka_operator.py", line 26, in generate_streams_data
    song_name = fake.song_name()
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/faker/proxy.py", line 130, in __getattr__
    return getattr(self._factories[0], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Generator' object has no attribute 'song_name'. Did you mean: 'month_name'?
[2025-08-04T22:53:16.385+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-04T22:53:16.447+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T22:53:16.455+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
